map_type: costmap
transform_tolerance: 0.5
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inscribed_radius: 0.35
circumscribed_radius: 0.4
inflation_radius: 0.50
cost_scaling_factor: 15.0
lethal_cost_threshold: 100
footprint_padding: 0.01

observation_sources: scan

scan: {sensor_frame; openni_camera, data_type: LaserScan, topic: /scan, expected_update_rate: 20.0, observation_persistance: 0.0, marking: true, clearing: true}
