/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-fuerte-turtlebot-1.0.2/debian/ros-fuerte-turtlebot/opt/ros/fuerte/stacks/turtlebot/turtlebot_node/msg/Turtle.msg */
#ifndef TURTLEBOT_NODE_MESSAGE_TURTLE_H
#define TURTLEBOT_NODE_MESSAGE_TURTLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace turtlebot_node
{
template <class ContainerAllocator>
struct Turtle_ {
  typedef Turtle_<ContainerAllocator> Type;

  Turtle_()
  : linear(0.0)
  , angular(0.0)
  {
  }

  Turtle_(const ContainerAllocator& _alloc)
  : linear(0.0)
  , angular(0.0)
  {
  }

  typedef float _linear_type;
  float linear;

  typedef float _angular_type;
  float angular;


  typedef boost::shared_ptr< ::turtlebot_node::Turtle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_node::Turtle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Turtle
typedef  ::turtlebot_node::Turtle_<std::allocator<void> > Turtle;

typedef boost::shared_ptr< ::turtlebot_node::Turtle> TurtlePtr;
typedef boost::shared_ptr< ::turtlebot_node::Turtle const> TurtleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::turtlebot_node::Turtle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::turtlebot_node::Turtle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace turtlebot_node

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::turtlebot_node::Turtle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::turtlebot_node::Turtle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_node::Turtle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const  ::turtlebot_node::Turtle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9d5c2dcd348ac8f7ULL;
  static const uint64_t static_value2 = 0x6ce2a4307bd63a13ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_node::Turtle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "turtlebot_node/Turtle";
  }

  static const char* value(const  ::turtlebot_node::Turtle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_node::Turtle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 linear\n\
float32 angular\n\
";
  }

  static const char* value(const  ::turtlebot_node::Turtle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::turtlebot_node::Turtle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::turtlebot_node::Turtle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.linear);
    stream.next(m.angular);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Turtle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_node::Turtle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::turtlebot_node::Turtle_<ContainerAllocator> & v) 
  {
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_NODE_MESSAGE_TURTLE_H

